### ISSUE TITLE
standardize lint setting

### ISSUE THREAD

**Issue by yafimvo** [ploomber/jupysql#331] opened 2023-03-28 15:03 UTC
We use flake8 and black to lint and format our code, notebooks, and docs. we invoke it by running `pkgmt lint` [read more here](https://github.com/ploomber/contributing/blob/main/CONTRIBUTING.md#coding)

Running `black` locally might modify unrelated files and apply lint changes based on our local settings (i.e: IDE).

To fix it we can:
1. Define a standard black lint setting
2. Make sure our local lint settings don't affect it
3. Add black phase to CI

References:
[Black configuration format](https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#configuration-format)

cc: @edublancas @idomic @tonykploomber

**Comment by edublancas** [comment] 2023-03-28 17:57
this sounds like a duplicate of https://github.com/ploomber/contributing/issues/44

**Closed by edublancas** 2023-03-28 17:57 UTC
