### ISSUE TITLE
Error when using %sqlplot in snowflake

### ISSUE THREAD

**Issue by juliusngcmc** [ploomber/jupysql#444] opened 2023-04-25 04:22 UTC
The issue relates to this [slack question](https://ploomber-io.slack.com/archives/C028KJCJDRT/p1682395550183859)
I try to use `sqlplot` to create a histogram
First, I create the table using `%%sql` and it works fine
```
%%sql --save date_count
select
    _INCREMENTAL_LOAD_DATE,
    count(*)
from DEV_LAKE.LAKE_OPTOMATE_2000_060.LAKE_OPTOMATE_2000_060_PATIENT
GROUP BY 1 ORDER BY 1
```

Then, when I try to create a histogram with `date_count` table:
```
%sqlplot histogram --table date_count --column _INCREMENTAL_LOAD_DATE --with date_count
```
I got this error:
`ProgrammingError: (snowflake.connector.errors.ProgrammingError) 002003 (42S02): SQL compilation error:
Object '"date_count"' does not exist or not authorized.
[SQL: WITH date_count AS (SELECT _INCREMENTAL_LOAD_DATE, COUNT(*) FROM DEV_LAKE.LAKE_OPTOMATE_2000_060.LAKE_OPTOMATE_2000_060_PATIENT GROUP BY 1 ORDER BY 1 NULLS FIRST) SELECT MIN("_INCREMENTAL_LOAD_DATE"), MAX("_INCREMENTAL_LOAD_DATE") FROM "date_count"]`

For some reason, the histogram query using `"date_count"` instead of `date_count (without Quotation marks)`
The data warehouse I'm using is Snowflake.
![image (2)](https://user-images.githubusercontent.com/110522861/234173964-51d1b5a3-60c8-4e83-9922-07c47e56080c.png)

**Comment by edublancas** [comment] 2023-04-25 21:57
Following up on this, the problem is a mismatch between sqlalchemy and snowflake when [handling identifiers](https://github.com/snowflakedb/snowflake-sqlalchemy#object-name-case-handling). We need to modify the internal SQL query we execute so it works.

We'll fix this soon!

**Comment by edublancas** [comment] 2023-06-21 16:14
@tonykploomber: did you start working on this? I can assign it to somebody else if not

**Comment by tonykploomber** [comment] 2023-06-29 21:26
I am checking on this, this is an interesting issue

Seems the issue was the double quote `"` that surrounds the table name

Problematic query in snowflake: `SELECT MIN('x'), MAX('x') FROM "PLOT_SOMETHING_02d39f"`

And this query seems work: `SELECT MIN('x'), MAX('x') FROM PLOT_SOMETHING_02d39f`

---

Possible Ad-hoc solution:

We may just remove the double quote `"` in all queries for snowflake case, but this method might affect the query statement provided by user, I need to see if this will effect other use-cases.

---

Some research on double quote identifier in snowflake

The double quote is used for case-sensitive case

Suppose we have a table created as `something`

Working statements: 

A. `select * from something`

B. `select * from SOMETHING`

C. `select * from "something"`

Not working statements:

A. select * from "SOMETHING"

**Comment by tonykploomber** [comment] 2023-06-30 02:05
The root cause:
1. Our plot query will generate the internal query like: `WITH plot_something_subset AS (SELECT * FROM PLOT_SOMETHING_524D8E LIMIT 3) SELECT MIN("x"), MAX("x") FROM "plot_something_subset"`

However, seems the above CTE is not working in snowflake database, it's the known issue we listed in [compability](https://jupysql.ploomber.io/en/latest/integrations/compatibility.html#snowflake), although we marked Plotting with `boxplot` and `histogram` as ❓


We need to make sure above CTE working in snowflake

**Comment by tonykploomber** [comment] 2023-07-05 18:18
@edublancas 

Yes, I did work on a portion of this task, we can see if this analysis make sense

## Root cause
Actually we shall support snowflake for the sqlplot.

The root cause is existing in our internal graphing queries.
For example, in one of query:
```
SELECT MIN('x'), MAX('x') FROM "PLOT_SOMETHING_02d39f"
```

We will use `"` quote symbol to wrap the table name.

However, in the snowflake, the `"` (double quote identifier) in snowflake is for case-sensitive purpose

## Approach

1. Maybe for the snowflake dialect, we can remove the `"` directly (using replace) while generating the internal graphing queries?

2. We might also see if [SQLglot](https://sqlglot.com/sqlglot.html) has option for this case

**Comment by edublancas** [comment] 2023-07-17 15:23
@tonykploomber any updates here? have you determined which is the best approach?

**Comment by tonykploomber** [comment] 2023-07-20 16:05
Yeah I think I pass the snowflake `%sqlplot histogram` issue in my PR, but that's suffering from other test cases failure.

Need to check more

**Comment by edublancas** [comment] 2023-08-18 20:13
@juliusngcmc we just fixed this! histograms will work on snowflake in the next release (0.10.0), which will be out in the next few days!

**Closed** 2023-08-18 20:13 UTC
Labels: stash, med complexity
