### ISSUE TITLE
`ggplot` API Histogram outputs Binder Error: Referenced column "None" not found in FROM clause

### ISSUE THREAD

**Issue by TegveerG** [ploomber/jupysql#769] opened 2023-07-28 20:51 UTC
I am facing this issue when working on the sql course (PR [here](https://github.com/ploomber/sql/pull/79)). I am using a table "all_vehicles" that is loaded in our DuckDB database and creating a CTE from it to call in `ggplot`.

 Before updating `Ploomber` from 0.22.4 to 0.22.5, the code below in my Jupyter Notebook was generating the histogram appropriately along with the widgets:
```
%%sql --save hist_co2 --no-execute
SELECT vehicle_type, mapped_fuel_type, co2emissions_g_km	
FROM all_vehicles
WHERE co2emissions_g_km is not null 
```
```
b = widgets.IntSlider(
    value=10,
    min=1,
    max=20,
    step=1,
    description="Bins:",
    orientation="horizontal",
)
cmap = widgets.Dropdown(
    options=["viridis", "plasma", "inferno", "magma", "cividis"],
    value="plasma",
    description="Colormap:",
    disabled=False,
)
fill = widgets.RadioButtons(
    options=["vehicle_type", "mapped_fuel_type"],
    description="Fill by:",
    disabled=False,
)
```
```
def co2_histogram(b, cmap, fill):
    (
        ggplot(
            table="hist_co2",
            with_="hist_co2",
            mapping=aes(x="co2emissions_g_km"),
        )  # noqa E501
        + geom_histogram(bins=b, fill=fill, cmap=cmap)
    )


interact(co2_histogram, b=b, cmap=cmap, fill=fill)
```

After the upgrade, the error message is as follows (sharing only the start and end because it's long):

```
---------------------------------------------------------------------------
BinderException                           Traceback (most recent call last)
File ~/miniforge3/envs/sqlcourse/lib/python3.10/site-packages/sqlalchemy/engine/base.py:1968, in Connection._exec_single_context(self, dialect, context, statement, parameters)
   1967     if not evt_handled:
-> 1968         self.dialect.do_execute(
   1969             cursor, str_statement, effective_parameters, context
   1970         )
   1972 if self._has_events or self.engine._has_events:

File ~/miniforge3/envs/sqlcourse/lib/python3.10/site-packages/sqlalchemy/engine/default.py:920, in DefaultDialect.do_execute(self, cursor, statement, parameters, context)
    919 def do_execute(self, cursor, statement, parameters, context=None):
--> 920     cursor.execute(statement, parameters)

File ~/miniforge3/envs/sqlcourse/lib/python3.10/site-packages/duckdb_engine/__init__.py:144, in ConnectionWrapper.execute(self, statement, parameters, context)
    143     else:
--> 144         self.__c.execute(statement, parameters)
    145 except RuntimeError as e:

BinderException: Binder Error: Referenced column "None" not found in FROM clause!
Candidate bindings: "hist_co2.vehicle_type"
LINE 1: ...UM(CASE WHEN FLOOR(co2emissions_g_km / None) * None = 0 THEN 1 ELSE 0 END) AS ...
...

File ~/miniforge3/envs/sqlcourse/lib/python3.10/site-packages/sqlalchemy/engine/default.py:920, in DefaultDialect.do_execute(self, cursor, statement, parameters, context)
    919 def do_execute(self, cursor, statement, parameters, context=None):
--> 920     cursor.execute(statement, parameters)

File ~/miniforge3/envs/sqlcourse/lib/python3.10/site-packages/duckdb_engine/__init__.py:144, in ConnectionWrapper.execute(self, statement, parameters, context)
    142         self.__c.execute(statement)
    143     else:
--> 144         self.__c.execute(statement, parameters)
    145 except RuntimeError as e:
    146     if e.args[0].startswith("Not implemented Error"):

ProgrammingError: (duckdb.BinderException) Binder Error: Referenced column "None" not found in FROM clause!
Candidate bindings: "hist_co2.vehicle_type"
LINE 1: ...UM(CASE WHEN FLOOR(co2emissions_g_km / None) * None = 0 THEN 1 ELSE 0 END) AS ...
```

**Comment by edublancas** [comment] 2023-07-28 21:40
it's more likely that this is a jupysql problem than a ploomber one. can you install ploomber 0.22.4 and try again? let me know if you get the same error (I think you will)

try downgrading jupysql, let me know if you find a version that works. and please share the full traceback (you can attach it as a file)

**Comment by TegveerG** [comment] 2023-07-29 03:04
@edublancas Downgrading to Ploomber 0.22.4 gives the same error. Also tried each version after downgrading JupySQL till 0.7.0 and got an error when creating the first CTE, so those didn't work either. 

Attached the traceback in a docx:

[ggplot_error_traceback.docx](https://github.com/ploomber/jupysql/files/12206147/ggplot_error_traceback.docx)

**Comment by edublancas** [comment] 2023-07-31 17:42
@TegveerG I'm gonna debug this. can you upload a notebook that allows me to reproduce the error?

should include code to download the data (preferably) or instructions on how to get it

**Comment by TegveerG** [comment] 2023-07-31 17:56
Sure. We have a notebook with the `ggplot` code as well as 3 `.py` files, one that retrieves the data and the others that help refactor the code in the notebook. I have migrated the code from the `.py` file that downloads the data and loads it into DuckDB. Keeping the attached files in a folder and running `voila-app copy.ipynb` should reproduce the error.

Edit: I cannot attach the files because they are unsupported. Should I send them over slack?

**Comment by edublancas** [comment] 2023-07-31 22:43
I reviewed the notebook and found the root cause, ggplot will fail if you attempt to plot non-numeric data. to fix the issue I did some manual casting:

```
SELECT vehicle_type, mapped_fuel_type,
    co2emissions_g_km::INTEGER as co2emissions_g_km -- added this!
FROM all_vehicles
WHERE co2emissions_g_km is not null 
```

![image](https://github.com/ploomber/jupysql/assets/989250/e1a71800-59d5-4764-8fe2-a4c9b82ce147)

not sure if this is the best way to the problem, probably better to do the casting to integer when you define the table

in any case, I'm leaving this open because we have to better handle this edge case and provide a better error message

**Comment by edublancas** [comment] 2023-08-01 03:55
closing in favor of https://github.com/ploomber/jupysql/issues/774

**Closed by edublancas** 2023-08-01 03:55 UTC
