### ISSUE TITLE
Writing code in parentheses in snippets causes inconsistent results in duck db (at least) compared to other dbs

### ISSUE THREAD

**Issue by nooodle-soup** [ploomber/jupysql#879] opened 2023-09-12 18:53 UTC
Wrapping a query in parentheses returns an empty result but works in duckdb.

```
In [2]: import duckdb

In [3]: conn = duckdb.connect()

In [4]: conn.execute("(select * from penguins.csv)").fetchall()
Out[4]:
[('Adelie', 'Torgersen', 39.1, 18.7, 181, 3750, 'MALE'),
 ('Adelie', 'Torgersen', 39.5, 17.4, 186, 3800, 'FEMALE'),
 ('Adelie', 'Torgersen', 40.3, 18.0, 195, 3250, 'FEMALE'),
 ('Adelie', 'Torgersen', None, None, None, None, None),
```

Running the following returns an empty table but the snippet is saved properly and works correctly when used in other
queries 

```
%%sql --save my_penguins
(select * from penguins.csv)
```

Need to look into how to print out the results when the query is wrapped in parentheses.

**Comment by edublancas** [comment] 2023-09-14 00:28
let's test this out with sqlite and postgres. if this only works with duckdb, then I think we can ignore it. otherwise, we can consider it a bug

**Comment by nooodle-soup** [comment] 2023-09-14 22:25
Okay
Will do!

**Comment by nooodle-soup** [comment] 2023-10-08 00:37
@edublancas I checked for the issue in sqlite, postgres and duckdb
Both duckdb and postgres allow parentheses wrapped queries.

The report for my findings is in the attached jupyter notebook.

[Issue871-tests.zip](https://github.com/ploomber/jupysql/files/12839499/Issue871-tests.zip)

**Comment by edublancas** [comment] 2023-10-09 17:19
ok, let's work on a fix then. I think the problem is that we're running some parsing on the SQL to detect the type of SQL statement and the parenthesis are causing trouble

**Comment by nooodle-soup** [comment] 2023-10-09 17:41
The parsing to detect the type of SQL statement does fail when the statement is wrapped in parentheses. `sqlparse.parse()` currently returns `UNKNOWN` for such queries. This can be fixed by removing the outermost parentheses of any query.

The second issue which would be solved with removing the parentheses would be CTE generation when queries are wrapped in parentheses, as the current code does not allow for `(with ` to return `True` for the `is_cte` check.

**Comment by edublancas** [comment] 2023-10-09 19:22
what is "the second issue"?

from what I understand, removing `( )` when parsing the query (to determine its type) should fix this

**Comment by nooodle-soup** [comment] 2023-10-10 03:54
Before getting the `query_type` of the query, it has to go through the `is_cte` check. We currently do not perform parsing here at all. We are just checking if the string starts with `with `. So when we have a query here that is a CTE but is wrapped in parentheses, before even parsing, it would set `is_cte` to `False`. This means that even though it is a CTE, it will never go to the correct control flow block. 

Currently, the get_query_type function takes in the original sql query, and unless we directly modify that, query expansion can become an issue. 

Example:
```
%%sql --save penguins
SELECT * FROM penguins.csv
```
```
`%%sql --w`ith penguins
(WITH my_penguins AS (
    SELECT * FROM penguins
)
SELECT * FROM my_penguins)
```

For the second cell, `is_cte` will evaluate to False even though it should evaluate to True.
Because a `--with` argument is used, the query will be expanded to the following.
```
WITH penguins AS (
SELECT * FROM penguins.csv)
(WITH my_penguins AS (
    SELECT * from penguins
)
SELECT * FROM my_penguins)]
```
This is the case where we do not parse the sql for query_type as it should never reach this part of the control flow if it is a CTE.

**Comment by edublancas** [comment] 2023-10-10 17:24
ok, so sounds like you identified how to proceed right? It's unclear if you need feedback from my end. sounds like we need better `is_cte` logic to fix this issue

**Comment by edublancas** [comment] 2023-10-10 20:29
sounds good!

**Comment by edublancas** [comment] 2023-11-29 13:47
there are many edge cases about this issue. given that this should not happen often, I'm closing it

**Closed by edublancas** 2023-11-29 13:47 UTC
