### ISSUE TITLE
Document `%config` for `SQLMagic.autocommit`

### ISSUE THREAD

**Issue by mehtamohit013** [ploomber/jupysql#709] opened 2023-07-05 14:04 UTC
Currently, docs don't contain any info on `SqlMagic.autocommit`.

Also, check out any other config options.

**Comment by edublancas** [comment] 2023-07-27 20:55
duplicate of https://github.com/ploomber/jupysql/issues/691

**Closed by edublancas** 2023-07-27 20:55 UTC
Labels: documentation
