### ISSUE TITLE
the version installed with conda didn't work

### ISSUE THREAD

**Issue by alexbodn** [ploomber/jupysql#718] opened 2023-07-09 13:15 UTC
hello friends,

and thank you for providing jupysql.
while the version installed with conda didn't work at all,
ipython-sql  was required,
pip install jupysql did the good trick,
and works as advertised.

thanks again,
alex

**Comment by edublancas** [comment] 2023-07-10 15:56
thanks for your feedback! can you share the problem you had? we'll take a look

**Comment by edublancas** [comment] 2023-07-25 02:00
@neelasha23 can you take a look at this?

**Comment by neelasha23** [comment] 2023-07-28 10:52
@alexbodn Please share the steps to reproduce the issue. Do include details like OS , Python version etc.

**Comment by neelasha23** [comment] 2023-07-31 16:06
Closing since we couldn't reproduce the error. @alexbodn Please feel free to re-open with more details if you are still facing the issue.

**Closed by neelasha23** 2023-07-31 16:06 UTC
