### ISSUE TITLE
support histogram when using a DBAPI connection

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql#728] opened 2023-07-12 21:27 UTC
when using a generic DBAPI connection, I get an error when trying to use boxplot:

```
In [1]: %load_ext sql

In [2]: import duckdb; conn = duckdb.connect()

In [3]: %sql conn

In [6]: %sql select * from iris.csv
Running query in '<duckdb.DuckDBPyConnection object at 0x11e1921f0>'
Out[6]:
+--------------+-------------+--------------+-------------+-------------+
| sepal length | sepal width | petal length | petal width |    class    |
+--------------+-------------+--------------+-------------+-------------+
|     5.1      |     3.5     |     1.4      |     0.2     | Iris-setosa |
|     4.9      |     3.0     |     1.4      |     0.2     | Iris-setosa |
|     4.7      |     3.2     |     1.3      |     0.2     | Iris-setosa |
|     4.6      |     3.1     |     1.5      |     0.2     | Iris-setosa |
|     5.0      |     3.6     |     1.4      |     0.2     | Iris-setosa |
|     5.4      |     3.9     |     1.7      |     0.4     | Iris-setosa |
|     4.6      |     3.4     |     1.4      |     0.3     | Iris-setosa |
|     5.0      |     3.4     |     1.5      |     0.2     | Iris-setosa |
|     4.4      |     2.9     |     1.4      |     0.2     | Iris-setosa |
|     4.9      |     3.1     |     1.5      |     0.1     | Iris-setosa |
+--------------+-------------+--------------+-------------+-------------+

In [7]: %sqlplot boxplot --table iris.csv --column class
Installed osx event loop hook.
RuntimeError: boxplot is not supported for a custom engine
If you need help solving this issue, send us a message: https://ploomber.io/community

```

the error is raised here: https://github.com/ploomber/jupysql/blob/aa360f9505c7b0e3ad8968cf38b2ccfc9df9d4a1/src/sql/plot.py#L145

and it suggests that we are not allowing it because some databases do not support the percentile disc function; however this doesn't have to do with being a dbapi connection or a sqlalchemy one. they'll both send the query to the db and the query will work just fine if it has the percentile_disc function

is there are other reason why we're not supporting it? @yafimvo

**Comment by mehtamohit013** [comment] 2023-07-14 06:28
@edublancas @yafimvo 
I am not quite sure what would be AC criteria here, do you want me to work on improving `sqlplot` with custom engine or a better error message when using custom engine?

**Comment by edublancas** [comment] 2023-07-14 14:17
we want histogram to work when using a DBAPI connection (at least with duckDB).

there is one line there preventing it from working: https://github.com/ploomber/jupysql/blob/aa360f9505c7b0e3ad8968cf38b2ccfc9df9d4a1/src/sql/plot.py#L145

and the error message says it's because the connection is a DBAPI connection but that shouldn't affect whether the histogram works or not. so we have to remove it and then figure out why it isn't working.

if DuckDB with SQLAlchemy works, then DuckDB with DBAPI should work as well because it's the same underlying database.

**Comment by mehtamohit013** [comment] 2023-07-14 15:17
AC Criteria
- Add support for DBAPI connection for histogram
- Tests
- Changelog

**Comment by edublancas** [comment] 2023-07-14 17:57
the ac looks good.

let's wait for @yafimvo's feedback but sharing some thoughts that can help you:

since we know that duckdb with sqlalchemy works, then allowing the dbapi (native connection) to work shouldn't require any changes to the underlying SQL that produces the data for the plot. However, when I tried it, I remember seeing some SQL error, so the first thing to investigate is why this is happening. I'd recommend you compare the outputs of duckdb sqlalchemy vs dbapi/native connection and see if you find any discrepancies.

**Comment by yafimvo** [comment] 2023-07-16 12:11
@edublancas @mehtamohit013 

This happens because of [this line](https://github.com/ploomber/jupysql/blob/master/src/sql/connection.py#L640):

```
query = self._transpile_query(query)
```

More specifically, it takes this query
```
SELECT PERCENTILE_DISC([0.25, 0.50, 0.75]) WITHIN GROUP (ORDER BY "body_mass_g") AS percentiles FROM "penguins.csv"
```

and turns it into
```
SELECT PERCENTILE_DISC(ARRAY(0.25, 0.50, 0.75)) WITHIN GROUP (ORDER BY "body_mass_g") AS percentiles FROM "penguins.csv"
``

native duckdb connection doesn't support passing an array to the percentile_disc method

`PERCENTILE_DISC(ARRAY(0.25, 0.50, 0.75))`


### Suggestion:
We can transpile queries only when using sqlalchemy

I added a [PR](https://github.com/ploomber/jupysql/pull/737) to see if this change affects our tests (besides the tests that expect this error message)

@tonykploomber since you were working on the transpile, any thoughts?

**Comment by edublancas** [comment] 2023-07-16 22:27
this seems like a bug in the in the `_transpile_logic` query because if the connection is DuckDB with SQLAlchemy or DuckDB DBAPI/native shouldn't make a difference. The code we send to the DB should be the same

**Comment by mehtamohit013** [comment] 2023-07-17 11:36
## Problem and Analysis

- So, the problem is wrong dialect detection: `_get_curr_sqlglot_dialect`
For native `duckdb` connection (`duckdb.connect()`), the following function return `None` but it should return `"duckdb"`

- If I pass, `dialect="duckdb"`, it return the following `query`, which is working:
`SELECT PERCENTILE_DISC(LIST_VALUE(0.25, 0.50, 0.75)) WITHIN GROUP (ORDER BY "body_mass_g" NULLS FIRST) AS percentiles FROM "penguins.csv"`

- This is due to `CustomConnection.session.dialect` being `{'name': 'custom_driver', 'driver': 'custom_driver', 'server_version_info': 'custom_driver'}`, which in turn has no attribute(`None`) when running [this](https://github.com/ploomber/jupysql/blob/c1f9cdf8d12a97067a4d6d131e08b88309d146f2/src/sql/connection.py#L520):
```python
return {
            "dialect": getattr(engine.dialect, "name", None),
            "driver": getattr(engine.dialect, "driver", None),
            "server_version_info": getattr(engine.dialect, "server_version_info", None),
        }
```


## Potential Solution
- I cannot find any custom detector to identify the SQL database from their connection object
- We have to change how `jupysql` handles custom connections by mapping object classes to their respective database such as `{'DuckDBPyConnection':"duckdb"}` using the logic `CustomConnection.session.engine.__class__.__name__` 

What do you think about this approach? @edublancas @yafimvo @tonykploomber

**Comment by yafimvo** [comment] 2023-07-17 12:59
@mehtamohit013 
I think @edublancas fixed it in this [PR](https://github.com/ploomber/jupysql/pull/725)

We didn't merge it yet but I suggest running some experiments on this version

**Comment by edublancas** [comment] 2023-07-17 13:29
@mehtamohit013: yes, in #725, I updated the code so a DBAPI/native connection accurately returns "duckdb" ([see here](https://github.com/ploomber/jupysql/blob/75913be9a2be46f52cfde9a5b35428453c83d75c/src/sql/connection.py#L700C37-L700C37)), we're going to merge that one soon so it's safe to use it.

**Comment by mehtamohit013** [comment] 2023-07-17 13:45
@edublancas 
I am quite sure after merging #725, the histogram issue will be solved for duckdb, so  what will be the AC criteria of this issue? Should I wait for #725 to be merged?

Some thoughts: I may be missing something, but the function [here](https://github.com/ploomber/jupysql/blob/75913be9a2be46f52cfde9a5b35428453c83d75c/src/sql/connection.py#L715), is a loosely bound(any engine with `df` and `pl` attribute can be duckdb, although that can be rare). A more concrete one would be checking if the engine is of type `DuckDBPyConnection`. We can also apply this approach to other native Python connectors offered by various databases.

**Comment by edublancas** [comment] 2023-07-17 15:50
@mehtamohit013: we still have a check that raises an exception if it detects that the connection is DBAPI so we have to remove that and add a unit test.

As for the df/pl thing, it'd be surprising that other connections add df/pl methods. I think we can follow the [duck typing](https://en.wikipedia.org/wiki/Duck_typing) principle here

**Comment by mehtamohit013** [comment] 2023-07-18 17:51
> we still have a check that raises an exception if it detects that the connection is DBAPI so we have to remove that

Histogram doesn't have that, boxplot has it. 

- Is the issue, adding support for histogram and boxplot for duckdb native connection or for general DBAPI connection? Because of the general DBAPI connection, we need to `_transpile_query` support for each DBAPI connection which is not possible because we cannot identify the dialect of a DBAPI connection(required for `boxplot` `PERCENTILE_DISC` function).

> add a unit test.

Currently, all the tests in [test_magic_plot.py](https://github.com/ploomber/jupysql/blob/master/src/tests/test_magic.py) runs on sqlalchemy duckdb connection, do you want me to test all of them for native duckdb(basically double the testing)

Raised initial PR with some changes: #745 
@edublancas

**Comment by tonykploomber** [comment] 2023-07-18 18:53
I think only drivers used by sqlalchemy will have [class Dialect](https://github.com/Mause/duckdb_engine/blob/b315c0777c84387cf7663fefcf3914bad909fa05/duckdb_engine/__init__.py#L169-L170) defined, where the source of the dialect name. 

However, this kind of custom driver might just follow [PEP 249](https://peps.python.org/pep-0249/) standard, but I don't see there is the clear session which contracts the name of dialect or driver

@mehtamohit013 
Ad-hoc solution of `_check_if_duckdb_dbapi_connection` seems to work for me, I think we can add the test case with duckdb native driver connection with boxplot here

It would be good if we can make different fixtures for connection via sqlalchemy and connection via it's native driver then test them together, like how we did in integration testing to separate different `ip_with_dynamic_db`. But I think this task is large and will be part of integration testing

**Comment by mehtamohit013** [comment] 2023-07-19 11:05
> Ad-hoc solution of _check_if_duckdb_dbapi_connection seems to work for me, I think we can add the test case with duckdb native driver connection with boxplot here

Sure

>It would be good if we can make different fixtures for connection via sqlalchemy and connection via it's native driver then test them together, like how we did in integration testing to separate different ip_with_dynamic_db. But I think this task is large and will be part of integration testing

Nice Idea

Heading the discussion over to PR #745

**Comment by edublancas** [comment] 2023-07-20 14:58
> Is the issue, adding support for histogram and boxplot for duckdb native connection or for general DBAPI connection? Because of the general DBAPI connection, we need to _transpile_query support for each DBAPI connection which is not possible because we cannot identify the dialect of a DBAPI connection(required for boxplot PERCENTILE_DISC function).

let's focus on duckdb

**Comment by edublancas** [comment] 2023-07-26 19:14
@mehtamohit013 let resume work on this one. we merged the refactoring PR.

I did a quick test: I removed the `util.support_only_sql_alchemy_connection("boxplot")` call in `plot.py` and then ran `test_sqlplot_boxplot` with duckdb native, the test passed but we need to ensure that the boxplot is actually displayed and it produces the some one as it would with duckdb + sqlalchemy

we also need to update the docs because the duckdb tutorial that uses native connections isn't showing the boxplot example

**Closed** 2023-08-01 14:52 UTC
Labels: stash
